# Generated by Django 2.2.5 on 2020-08-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=100)),
                ('sub_category', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('prod_desc', models.CharField(max_length=350)),
                ('pub_time', models.DateField()),
                ('image', models.ImageField(default='', upload_to='myagri/images')),
            ],
        ),
    ]
