# Generated by Django 2.2.5 on 2020-08-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myagri', '0004_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='Price',
            field=models.IntegerField(default='0'),
        ),
    ]
