# Generated by Django 2.2.5 on 2020-08-14 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myagri', '0005_auto_20200814_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Price',
        ),
    ]
