# Generated by Django 2.2.5 on 2020-08-14 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myagri', '0007_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Price',
        ),
    ]
